version: "3.9"

services:
  mariadb:
    image: "mariadb:latest"
    container_name: mariadb
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
      - "./logs:/var/log/mysql"
      - "/var/docker/mariadb/conf:/etc/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "heticdb"
      MYSQL_USER: "hetic"
      MYSQL_PASSWORD: "hetic"
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "40001:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - wp_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: heticdb
      WORDPRESS_DB_USER: hetic
      WORDPRESS_DB_PASSWORD: hetic
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp_network

volumes:
  mariadb_data:
  wordpress_data:

networks:
  wp_network:
